# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 05:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0002_remove_temperaturesensor_pub_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturesensor',
            name='pub_time',
            field=models.DateField(null=True),
        ),
    ]
