# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 00:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_auto_20170729_0115'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartbeatMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heartRate', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('pub_time', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ('heartbeatSensor',),
            },
        ),
        migrations.AlterModelOptions(
            name='heartbeatsensor',
            options={'ordering': ('deviceId',)},
        ),
        migrations.AddField(
            model_name='heartbeatsensor',
            name='create_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='heartbeatsensor',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='heartbeatsensor',
            name='type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='heartbeatmsg',
            name='heartbeatSensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heartbeatMsgs', to='sensor.HeartbeatSensor'),
        ),
    ]
