# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-25 06:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0003_temperaturesensor_pub_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='temperaturesensor',
            name='maxTemperature',
            field=models.FloatField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='temperaturesensor',
            name='minTemperature',
            field=models.FloatField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='temperaturesensor',
            name='temperature',
            field=models.FloatField(max_length=32, null=True),
        ),
    ]
