# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 02:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0004_auto_20170730_0054'),
    ]

    operations = [
        migrations.CreateModel(
            name='HallSensorMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MagnetiStrength', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('pub_time', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ('hallMagneticSensor',),
            },
        ),
        migrations.AlterModelOptions(
            name='hallmagneticsensor',
            options={'ordering': ('deviceId',)},
        ),
        migrations.AddField(
            model_name='hallmagneticsensor',
            name='SettingMagnetic',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='hallmagneticsensor',
            name='create_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hallmagneticsensor',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hallmagneticsensor',
            name='type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='hallsensormsg',
            name='hallMagneticSensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hallSensorMsgs', to='sensor.HallMagneticSensor'),
        ),
    ]
