# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-30 02:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sensor', '0005_auto_20170730_0209'),
    ]

    operations = [
        migrations.CreateModel(
            name='SoundSensorMsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('xAxis', models.FloatField()),
                ('yAxis', models.FloatField()),
                ('status', models.BooleanField(default=False)),
                ('pub_time', models.DateField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ('soundSensor',),
            },
        ),
        migrations.AlterModelOptions(
            name='soundsensor',
            options={'ordering': ('deviceId',)},
        ),
        migrations.AddField(
            model_name='soundsensor',
            name='create_time',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='soundsensor',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='soundsensor',
            name='type',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='soundsensormsg',
            name='soundSensor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soundSensorMsgs', to='sensor.SoundSensor'),
        ),
    ]
